from typing import Dict, List, Optional, Tuple

from .models import IntermediateFlowRow


def parse_intermediate_flows(path: str) -> Dict[str, List[IntermediateFlowRow]]:
    rows_by_component: Dict[str, List[IntermediateFlowRow]] = {}

    with open(path, "r") as f:
        header = f.readline().rstrip("\n")
        if not header:
            return rows_by_component

        expected_prefix = "kind\tcomponent\torder\tuuid"
        if not header.startswith(expected_prefix):
            raise ValueError(
                f"Invalid intermediate file header in {path}; expected TSV generated by this tool"
            )

        for raw_line in f:
            line = raw_line.rstrip("\n")
            if not line:
                continue

            cols = line.split("\t")
            # Keep compatibility if data_trace contains tabs by joining tail columns.
            if len(cols) > 14:
                cols = cols[:13] + ["\t".join(cols[13:])]
            if len(cols) < 14:
                continue

            kind = cols[0]
            if kind != "flow":
                continue

            row = IntermediateFlowRow(
                component=cols[1],
                order=int(cols[2]) if cols[2] else -1,
                uuid=int(cols[3]) if cols[3] else -1,
                wid=cols[4],
                first_cycle=cols[5],
                last_cycle=cols[6],
                pc=cols[7],
                tmask=cols[8],
                function=cols[9],
                instruction=cols[10],
                stages=cols[11],
                stage_complete=cols[12],
                data_trace=cols[13],
            )

            if row.component not in rows_by_component:
                rows_by_component[row.component] = []
            rows_by_component[row.component].append(row)

    for component in rows_by_component:
        rows_by_component[component].sort(key=lambda r: r.order)

    return rows_by_component


def first_list_difference(a: List[str], b: List[str]) -> Optional[Tuple[int, str, str]]:
    limit = min(len(a), len(b))
    for idx in range(limit):
        if a[idx] != b[idx]:
            return (idx, a[idx], b[idx])
    if len(a) != len(b):
        extra_a = a[limit] if len(a) > limit else "<none>"
        extra_b = b[limit] if len(b) > limit else "<none>"
        return (limit, extra_a, extra_b)
    return None


def compare_flow_rows(row_a: IntermediateFlowRow, row_b: IntermediateFlowRow) -> Optional[str]:
    field_pairs = [
        ("wid", row_a.wid, row_b.wid),
        ("pc", row_a.pc, row_b.pc),
        ("tmask", row_a.tmask, row_b.tmask),
        ("function", row_a.function, row_b.function),
        ("instruction", row_a.instruction, row_b.instruction),
        ("stages", row_a.stages, row_b.stages),
        ("stage_complete", row_a.stage_complete, row_b.stage_complete),
    ]

    for field_name, a_val, b_val in field_pairs:
        if a_val != b_val:
            return f"field={field_name}, A={a_val}, B={b_val}"

    trace_a = [x.strip() for x in row_a.data_trace.split("||") if x.strip()]
    trace_b = [x.strip() for x in row_b.data_trace.split("||") if x.strip()]
    diff = first_list_difference(trace_a, trace_b)
    if diff is not None:
        idx, a_item, b_item = diff
        return f"field=data_trace[{idx}], A={a_item}, B={b_item}"

    return None


def trim_rows_before_kernel_reset(
    rows: List[IntermediateFlowRow],
) -> Tuple[List[IntermediateFlowRow], bool]:
    """
    Drop all rows before the first kernel reset marker (PC=0x80000000).

    Returns (trimmed_rows, found_reset_marker).
    """
    # Prefer exact reset PC if present.
    for idx, row in enumerate(rows):
        if row.pc.lower() == "0x80000000":
            return (rows[idx:], True)

    # In many traces, reset records use uuid=0 and are not part of flow rows.
    # Fall back to the first boot-schedule flow in the kernel text region.
    for idx, row in enumerate(rows):
        if "schedule" not in row.stages:
            continue

        try:
            pc_val = int(row.pc, 16)
        except ValueError:
            continue

        if 0x80000000 <= pc_val <= 0x80001000:
            return (rows[idx:], True)

    # Additional fallback: first scheduled _start flow if present.
    for idx, row in enumerate(rows):
        if row.function == "_start" and "schedule" in row.stages:
            return (rows[idx:], True)

    return (rows, False)


def render_intermediate_comparison(
    tsv_a: str,
    tsv_b: str,
    label_a: str,
    label_b: str,
) -> str:
    flows_a = parse_intermediate_flows(tsv_a)
    flows_b = parse_intermediate_flows(tsv_b)

    lines: List[str] = []
    lines.append("# Intermediate Trace Comparison")
    lines.append(f"A: {label_a} ({tsv_a})")
    lines.append(f"B: {label_b} ({tsv_b})")
    lines.append("")

    components = sorted(set(flows_a.keys()) | set(flows_b.keys()))
    if not components:
        lines.append("No flow rows found in either input.")
        return "\n".join(lines)

    mismatch_count = 0
    lines.append("Per-component first divergence (starting from kernel reset PC=0x80000000):")
    for component in components:
        rows_a = flows_a.get(component, [])
        rows_b = flows_b.get(component, [])
        rows_a, reset_found_a = trim_rows_before_kernel_reset(rows_a)
        rows_b, reset_found_b = trim_rows_before_kernel_reset(rows_b)

        lines.append(f"  {component}:")
        lines.append(
            f"    reset-marker: A={'found' if reset_found_a else 'missing'}, B={'found' if reset_found_b else 'missing'}"
        )

        if not rows_a and not rows_b:
            lines.append("    no rows in either file")
            continue
        if not rows_a:
            mismatch_count += 1
            lines.append("    missing in A; present in B")
            continue
        if not rows_b:
            mismatch_count += 1
            lines.append("    present in A; missing in B")
            continue

        limit = min(len(rows_a), len(rows_b))
        found = False
        for idx in range(limit):
            row_a = rows_a[idx]
            row_b = rows_b[idx]
            detail = compare_flow_rows(row_a, row_b)
            if detail is not None:
                mismatch_count += 1
                lines.append(
                    f"    first mismatch at order={row_a.order} uuid(A)={row_a.uuid} uuid(B)={row_b.uuid}"
                )
                lines.append(f"    {detail}")
                found = True
                break

        if not found and len(rows_a) != len(rows_b):
            mismatch_count += 1
            lines.append(
                f"    length mismatch after order={rows_a[limit - 1].order if limit > 0 else 0}: "
                f"len(A)={len(rows_a)} len(B)={len(rows_b)}"
            )
            found = True

        if not found:
            lines.append("    no mismatch")

    lines.append("")
    lines.append(f"Summary: components={len(components)}, mismatching-components={mismatch_count}")
    return "\n".join(lines)
